---
version: "3.8"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - PUID=1001
      - PGID=1001
      - VERSION=docker
      - PLEX_CLAIM=claim-JqKmMibymkhjQMNw2g_w
      - DOCKER_MODS=linuxserver/mods:plex-absolute-hama
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /home/kyle/PlexInDocker/appdata/config:/config
      - /media/sda1/Movies - Covington - 2019:/movies-sda1-1
      - /media/sda1/Movies - Louisville - 2020:/movies-sda1-2
      - /media/sda1/TV Shows:/tv-sda1-1
      - /media/sda1/Music:/music-sda1-1
    restart: unless-stopped
